title: Fantasy Football Prediction

top-section-bg-text: Fantasy Football Prediction
backgrounds:
  - static/assets/background/CASE_Ralphie1GA.JPG
background-interval-ms: 7000
background-overlay: 0.3
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/trma2416/CSCI_5502_Fantasy_Project
license-link:
  text: License
  href: https://github.com/senli1073/senli1073.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: INTRODUCTION
    href: '#page-top' # Default to '#<id>' if not specified
  - id: about
    nav: ABOUT
    title: ABOUT US
    icon: bi-about-fill
  - id: proposal
    nav: PROPOSAL
    title: PROPOSAL
    icon: bi-proposal-fill
  - id: background
    nav: BACKGROUND
    title: BACKGROUND
    icon: bi-background-fill